### ISSUE TITLE
EWAS only sometimes raises an error when outcome NAs are not removed

### ISSUE THREAD

**Issue by tomszar** [HallLab/clarite-python#99]
When running an EWAS and the outcome variable has NAs, sometimes an error is raised `ValueError: too few complete observations (min_n filter: 0 < 200)`. Not sure what other conditions should be met to reproduce the same error because, at other times when running an EWAS with an outcome variable also containing NAs, the error is not raised. When removing the NA rows before running the EWAS, the analysis runs well. Should there be a way to internally remove the NA rows without raising an error, or why this happens only in some instances and not others?

To reproduce: Run the following code using the [ExampleData.csv](https://github.com/HallLab/clarite-python/files/6511501/ExampleData.csv). The first EWAS, without the outcome NAs removed, should raise the error, while the second shouldn't

```python
import clarite
import pandas as pd

# Load dataset
dat = pd.read_csv('ExampleData.csv').set_index('ID')
dat = clarite.modify.categorize(dat)

# First EWAS. Should raise an error
res = clarite.analyze.ewas(outcome = 'LBXBAP',
                     covariates = ['black'],
                     min_n = 200,
                     data = dat)

# Second EWAS, after removing NAs from outcome. Should not raise an error
dat2 = clarite.modify.rowfilter_incomplete_obs(dat, only=['LBXBAP'])
res = clarite.analyze.ewas(outcome = 'LBXBAP',
                     covariates = ['black'],
                     min_n = 200,
                     data = dat2)

```

**Comment by jrm5100** [comment]
NA values in the outcome are automatically dropped.  This sometimes affects variables being regressed.  In this case, the three variables only have data when the outcome is NA, so removing those samples removes all data from these variables.

In the first run, the three variants are valid categorical variables when passed into the regression.  During the analysis, samples with NA outcome values are removed automatically:

```
Using 1,237 of 4,751 observations
	3,514 are missing a value for the outcome variable
```

After removing these, each variable must have the minimum number of non-NA observations and these variables fail the check:

```
3 tests had an error
	DRD350B = NULL due to: too few complete observations (min_n filter: 0 < 200)
	DRD370M = NULL due to: too few complete observations (min_n filter: 0 < 200)
	DRD370A = NULL due to: too few complete observations (min_n filter: 0 < 200)
```

In the second run,  you have removed NA values in the outcome yourself, leaving these variables with no data before they are passed to the ewas function.  CLARITE datatypes don't use native pandas datatypes (this is something I'd love to fix in the future with ExtensionArrays, but it would be some work) and so it has to determine the datatypes everytime data is accepted.  In the second run the `_get_dtypes` function assigns an "unknown" type to these variables (since they have no unique values) and they are skipped before getting to the minimum n check:

```
Warning: 3 variables had empty categories (the category exists in the data type, but doesn't occur in any observations):
	DRD350B missing '0.0', '1.0'
	DRD370M missing '0.0', '1.0'
	DRD370A missing '0.0', '1.0'
WARNING: 3 variables need to be categorized into a type manually
```

You can see the difference:

```
Regressing 0 variables
	9 binary variables
	1 categorical variables
	0 continuous variables
```

vs 

```
Regressing 0 variables
	6 binary variables
	1 categorical variables
	0 continuous variables
```

Also I just made a fix for that "Regressing 0 variables" line.

**Comment by tomszar** [comment]
I see! That makes sense. I think is safer to drop the outcome NAs before running the ewas then
